name: Build Documentation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.12.0
        with: { working-directory: docs }